// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0EDmjszfnmGR0m0ouIMn7vRhXRrxiKiA',
    appId: '1:771138066392:web:e5d6a4c447f7519fe6c4ad',
    messagingSenderId: '771138066392',
    projectId: 'tagginapp',
    authDomain: 'taggin.app', // <--- UPDATED LINE
    storageBucket: 'tagginapp.firebasestorage.app',
    measurementId: 'G-V0D1LK6PSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvfzrnaCcipGUXu-99CE_Qa4w2r4GblMc',
    appId: '1:771138066392:android:e8184f1b22e11833e6c4ad',
    messagingSenderId: '771138066392',
    projectId: 'tagginapp',
    storageBucket: 'tagginapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2bGGCs9vIT5TPN8xa6I01P__z5rAswxM',
    appId: '1:771138066392:ios:0f0b260cfa0a2f0de6c4ad',
    messagingSenderId: '771138066392',
    projectId: 'tagginapp',
    storageBucket: 'tagginapp.firebasestorage.app',
    androidClientId: '771138066392-0gledndjaj7es98msp58ras875gd35m0.apps.googleusercontent.com',
    iosClientId: '771138066392-tv90k713kj8jsl2biq6jndnmneukbprb.apps.googleusercontent.com',
    iosBundleId: 'com.example.tagginApk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2bGGCs9vIT5TPN8xa6I01P__z5rAswxM',
    appId: '1:771138066392:ios:0f0b260cfa0a2f0de6c4ad',
    messagingSenderId: '771138066392',
    projectId: 'tagginapp',
    storageBucket: 'tagginapp.firebasestorage.app',
    androidClientId: '771138066392-0gledndjaj7es98msp58ras875gd35m0.apps.googleusercontent.com',
    iosClientId: '771138066392-tv90k713kj8jsl2biq6jndnmneukbprb.apps.googleusercontent.com',
    iosBundleId: 'com.example.tagginApk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0EDmjszfnmGR0m0ouIMn7vRhXRrxiKiA',
    appId: '1:771138066392:web:f1241198397058d2e6c4ad',
    messagingSenderId: '771138066392',
    projectId: 'tagginapp',
    authDomain: 'tagginapp.firebaseapp.com',
    storageBucket: 'tagginapp.firebasestorage.app',
    measurementId: 'G-RG6CQK4YSM',
  );
}
